# IMPORTANT:
# Do not put real secrets in this file.
# Add the following machine-specific values to application-local.properties:
# - spring.datasource.url
# - spring.datasource.username
# - spring.datasource.password
# - spring.mail.username
# - spring.mail.password
# - spring.security.oauth2.client.registration.azure.client-id
# - spring.security.oauth2.client.registration.azure.client-secret
# - spring.security.oauth2.client.registration.azure.client-authentication-method
# - spring.security.oauth2.client.provider.azure.issuer-uri

spring.datasource.url=${DB_URL}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.profiles.active=local

spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_schema=dbo
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

spring.thymeleaf.cache=false

# ——— Mail account (Office 365) ———
spring.mail.host=smtp.office365.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000

# =========================
# Microsoft Entra ID / SSO http://localhost:8080/api/me
# =========================
#spring.cloud.azure.active-directory.enabled=true
spring.security.oauth2.client.registration.azure.scope=openid,profile,email
spring.security.oauth2.client.registration.azure.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.azure.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.azure.client-name=Microsoft

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=TRACE
logging.level.com.azure.spring=DEBUG
# From must be allowed for the mailbox.
#app.mail.from=kycdatabase@treppides.com

#app.ui.baseurl=https://tools.treppides.com:8080/
